
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2017-03-14T17:54:12.661+01:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ReportExecutionService",
                      portName = "ReportExecutionServiceSoap12",
                      targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices",
                      wsdlLocation = "http://reports2.grant-thornton.fr/reportserver/ReportExecution2005.asmx?wsdl",
                      endpointInterface = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap")
                      
public class ReportExecutionServiceSoap12Impl implements ReportExecutionServiceSoap {

    private static final Logger LOG = Logger.getLogger(ReportExecutionServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadDrillthroughTarget(java.lang.String  drillthroughID )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo loadDrillthroughTarget(java.lang.String drillthroughID) { 
        LOG.info("Executing operation loadDrillthroughTarget");
        System.out.println(drillthroughID);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#setExecutionParameters2(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue  parameters ,)java.lang.String  parameterLanguage )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 setExecutionParameters2(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue parameters,java.lang.String parameterLanguage) { 
        LOG.info("Executing operation setExecutionParameters2");
        System.out.println(parameters);
        System.out.println(parameterLanguage);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#getRenderResource(java.lang.String  format ,)java.lang.String  deviceInfo ,)byte[]  result ,)java.lang.String  mimeType )*
     */
    public void getRenderResource(java.lang.String format,java.lang.String deviceInfo,javax.xml.ws.Holder<byte[]> result,javax.xml.ws.Holder<java.lang.String> mimeType) { 
        LOG.info("Executing operation getRenderResource");
        System.out.println(format);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadReport2(java.lang.String  report ,)java.lang.String  historyID )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 loadReport2(java.lang.String report,java.lang.String historyID) { 
        LOG.info("Executing operation loadReport2");
        System.out.println(report);
        System.out.println(historyID);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#logoff(*
     */
    public void logoff() { 
        LOG.info("Executing operation logoff");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#setExecutionCredentials(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials  credentials )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo setExecutionCredentials(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials credentials) { 
        LOG.info("Executing operation setExecutionCredentials");
        System.out.println(credentials);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#renderStream(java.lang.String  format ,)java.lang.String  streamID ,)java.lang.String  deviceInfo ,)byte[]  result ,)java.lang.String  encoding ,)java.lang.String  mimeType )*
     */
    public void renderStream(java.lang.String format,java.lang.String streamID,java.lang.String deviceInfo,javax.xml.ws.Holder<byte[]> result,javax.xml.ws.Holder<java.lang.String> encoding,javax.xml.ws.Holder<java.lang.String> mimeType) { 
        LOG.info("Executing operation renderStream");
        System.out.println(format);
        System.out.println(streamID);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#render(java.lang.String  format ,)java.lang.String  deviceInfo ,)byte[]  result ,)java.lang.String  extension ,)java.lang.String  mimeType ,)java.lang.String  encoding ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning  warnings ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString  streamIds )*
     */
    public void render(java.lang.String format,java.lang.String deviceInfo,javax.xml.ws.Holder<byte[]> result,javax.xml.ws.Holder<java.lang.String> extension,javax.xml.ws.Holder<java.lang.String> mimeType,javax.xml.ws.Holder<java.lang.String> encoding,javax.xml.ws.Holder<ArrayOfWarning> warnings,javax.xml.ws.Holder<ArrayOfString> streamIds) { 
        LOG.info("Executing operation render");
        System.out.println(format);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String extensionValue = "";
            extension.value = extensionValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString streamIdsValue = null;
            streamIds.value = streamIdsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#navigateDocumentMap(java.lang.String  docMapID )*
     */
    public int navigateDocumentMap(java.lang.String docMapID) { 
        LOG.info("Executing operation navigateDocumentMap");
        System.out.println(docMapID);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#resetExecution2(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 resetExecution2() { 
        LOG.info("Executing operation resetExecution2");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadReportDefinition2(byte[]  definition ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2  executionInfo ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning  warnings )*
     */
    public void loadReportDefinition2(byte[] definition,javax.xml.ws.Holder<ExecutionInfo2> executionInfo,javax.xml.ws.Holder<ArrayOfWarning> warnings) { 
        LOG.info("Executing operation loadReportDefinition2");
        System.out.println(definition);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#getExecutionInfo(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo getExecutionInfo() { 
        LOG.info("Executing operation getExecutionInfo");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadDrillthroughTarget2(java.lang.String  drillthroughID )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 loadDrillthroughTarget2(java.lang.String drillthroughID) { 
        LOG.info("Executing operation loadDrillthroughTarget2");
        System.out.println(drillthroughID);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#sort2(java.lang.String  sortItem ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum  direction ,)boolean  clear ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode  paginationMode ,)java.lang.Integer  pageNumber ,)java.lang.String  reportItem ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2  executionInfo )*
     */
    public void sort2(java.lang.String sortItem,com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum direction,boolean clear,com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode paginationMode,javax.xml.ws.Holder<java.lang.Integer> pageNumber,javax.xml.ws.Holder<java.lang.String> reportItem,javax.xml.ws.Holder<ExecutionInfo2> executionInfo) { 
        LOG.info("Executing operation sort2");
        System.out.println(sortItem);
        System.out.println(direction);
        System.out.println(clear);
        System.out.println(paginationMode);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String reportItemValue = "";
            reportItem.value = reportItemValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#listRenderingExtensions(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfExtension listRenderingExtensions() { 
        LOG.info("Executing operation listRenderingExtensions");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfExtension _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#findString(int  startPage ,)int  endPage ,)java.lang.String  findValue )*
     */
    public int findString(int startPage,int endPage,java.lang.String findValue) { 
        LOG.info("Executing operation findString");
        System.out.println(startPage);
        System.out.println(endPage);
        System.out.println(findValue);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#getExecutionInfo2(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 getExecutionInfo2() { 
        LOG.info("Executing operation getExecutionInfo2");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#render2(java.lang.String  format ,)java.lang.String  deviceInfo ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode  paginationMode ,)byte[]  result ,)java.lang.String  extension ,)java.lang.String  mimeType ,)java.lang.String  encoding ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning  warnings ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString  streamIds )*
     */
    public void render2(java.lang.String format,java.lang.String deviceInfo,com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode paginationMode,javax.xml.ws.Holder<byte[]> result,javax.xml.ws.Holder<java.lang.String> extension,javax.xml.ws.Holder<java.lang.String> mimeType,javax.xml.ws.Holder<java.lang.String> encoding,javax.xml.ws.Holder<ArrayOfWarning> warnings,javax.xml.ws.Holder<ArrayOfString> streamIds) { 
        LOG.info("Executing operation render2");
        System.out.println(format);
        System.out.println(deviceInfo);
        System.out.println(paginationMode);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String extensionValue = "";
            extension.value = extensionValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString streamIdsValue = null;
            streamIds.value = streamIdsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#getDocumentMap(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.DocumentMapNode getDocumentMap() { 
        LOG.info("Executing operation getDocumentMap");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.DocumentMapNode _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#logonUser(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  authority )*
     */
    public void logonUser(java.lang.String userName,java.lang.String password,java.lang.String authority) { 
        LOG.info("Executing operation logonUser");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(authority);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#listSecureMethods(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString listSecureMethods() { 
        LOG.info("Executing operation listSecureMethods");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#navigateBookmark(java.lang.String  bookmarkID ,)java.lang.Integer  pageNumber ,)java.lang.String  uniqueName )*
     */
    public void navigateBookmark(java.lang.String bookmarkID,javax.xml.ws.Holder<java.lang.Integer> pageNumber,javax.xml.ws.Holder<java.lang.String> uniqueName) { 
        LOG.info("Executing operation navigateBookmark");
        System.out.println(bookmarkID);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String uniqueNameValue = "";
            uniqueName.value = uniqueNameValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadReport(java.lang.String  report ,)java.lang.String  historyID )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo loadReport(java.lang.String report,java.lang.String historyID) { 
        LOG.info("Executing operation loadReport");
        System.out.println(report);
        System.out.println(historyID);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#loadReportDefinition(byte[]  definition ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo  executionInfo ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning  warnings )*
     */
    public void loadReportDefinition(byte[] definition,javax.xml.ws.Holder<ExecutionInfo> executionInfo,javax.xml.ws.Holder<ArrayOfWarning> warnings) { 
        LOG.info("Executing operation loadReportDefinition");
        System.out.println(definition);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo executionInfoValue = null;
            executionInfo.value = executionInfoValue;
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#toggleItem(java.lang.String  toggleID )*
     */
    public boolean toggleItem(java.lang.String toggleID) { 
        LOG.info("Executing operation toggleItem");
        System.out.println(toggleID);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#sort(java.lang.String  sortItem ,)com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum  direction ,)boolean  clear ,)java.lang.Integer  pageNumber ,)java.lang.String  reportItem ,)java.lang.Integer  numPages )*
     */
    public void sort(java.lang.String sortItem,com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum direction,boolean clear,javax.xml.ws.Holder<java.lang.Integer> pageNumber,javax.xml.ws.Holder<java.lang.String> reportItem,javax.xml.ws.Holder<java.lang.Integer> numPages) { 
        LOG.info("Executing operation sort");
        System.out.println(sortItem);
        System.out.println(direction);
        System.out.println(clear);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String reportItemValue = "";
            reportItem.value = reportItemValue;
            java.lang.Integer numPagesValue = null;
            numPages.value = numPagesValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#setExecutionParameters(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue  parameters ,)java.lang.String  parameterLanguage )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo setExecutionParameters(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue parameters,java.lang.String parameterLanguage) { 
        LOG.info("Executing operation setExecutionParameters");
        System.out.println(parameters);
        System.out.println(parameterLanguage);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#setExecutionCredentials2(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials  credentials )*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 setExecutionCredentials2(com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials credentials) { 
        LOG.info("Executing operation setExecutionCredentials2");
        System.out.println(credentials);
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ReportExecutionServiceSoap#resetExecution(*
     */
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo resetExecution() { 
        LOG.info("Executing operation resetExecution");
        try {
            com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
