package com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2017-03-14T17:54:12.692+01:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", name = "ReportExecutionServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ReportExecutionServiceSoap {

    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadDrillthroughTarget")
    @WebMethod(operationName = "LoadDrillthroughTarget", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget")
    @ResponseWrapper(localName = "LoadDrillthroughTargetResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadDrillthroughTargetResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo loadDrillthroughTarget(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String drillthroughID
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionParameters2")
    @WebMethod(operationName = "SetExecutionParameters2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters2")
    @ResponseWrapper(localName = "SetExecutionParameters2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionParameters2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 setExecutionParameters2(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String parameterLanguage
    );

    @RequestWrapper(localName = "GetRenderResource", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetRenderResource")
    @WebMethod(operationName = "GetRenderResource", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetRenderResource")
    @ResponseWrapper(localName = "GetRenderResourceResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetRenderResourceResponse")
    public void getRenderResource(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReport2")
    @WebMethod(operationName = "LoadReport2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport2")
    @ResponseWrapper(localName = "LoadReport2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReport2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 loadReport2(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String historyID
    );

    @RequestWrapper(localName = "Logoff", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Logoff")
    @WebMethod(operationName = "Logoff", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Logoff")
    @ResponseWrapper(localName = "LogoffResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LogoffResponse")
    public void logoff();

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionCredentials")
    @WebMethod(operationName = "SetExecutionCredentials", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials")
    @ResponseWrapper(localName = "SetExecutionCredentialsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionCredentialsResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo setExecutionCredentials(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials credentials
    );

    @RequestWrapper(localName = "RenderStream", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.RenderStream")
    @WebMethod(operationName = "RenderStream", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/RenderStream")
    @ResponseWrapper(localName = "RenderStreamResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.RenderStreamResponse")
    public void renderStream(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "StreamID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String streamID,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType
    );

    @RequestWrapper(localName = "Render", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Render")
    @WebMethod(operationName = "Render", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render")
    @ResponseWrapper(localName = "RenderResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.RenderResponse")
    public void render(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> extension,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings,
        @WebParam(mode = WebParam.Mode.OUT, name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfString> streamIds
    );

    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "NavigateDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.NavigateDocumentMap")
    @WebMethod(operationName = "NavigateDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateDocumentMap")
    @ResponseWrapper(localName = "NavigateDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.NavigateDocumentMapResponse")
    public int navigateDocumentMap(
        @WebParam(name = "DocMapID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String docMapID
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ResetExecution2")
    @WebMethod(operationName = "ResetExecution2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution2")
    @ResponseWrapper(localName = "ResetExecution2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ResetExecution2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 resetExecution2();

    @RequestWrapper(localName = "LoadReportDefinition2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReportDefinition2")
    @WebMethod(operationName = "LoadReportDefinition2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition2")
    @ResponseWrapper(localName = "LoadReportDefinition2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReportDefinition2Response")
    public void loadReportDefinition2(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(mode = WebParam.Mode.OUT, name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo2> executionInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetExecutionInfo")
    @WebMethod(operationName = "GetExecutionInfo", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo")
    @ResponseWrapper(localName = "GetExecutionInfoResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetExecutionInfoResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo getExecutionInfo();

    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadDrillthroughTarget2")
    @WebMethod(operationName = "LoadDrillthroughTarget2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget2")
    @ResponseWrapper(localName = "LoadDrillthroughTarget2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadDrillthroughTarget2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 loadDrillthroughTarget2(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String drillthroughID
    );

    @RequestWrapper(localName = "Sort2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Sort2")
    @WebMethod(operationName = "Sort2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort2")
    @ResponseWrapper(localName = "Sort2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Sort2Response")
    public void sort2(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode paginationMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> reportItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo2> executionInfo
    );

    @WebResult(name = "Extensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListRenderingExtensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ListRenderingExtensions")
    @WebMethod(operationName = "ListRenderingExtensions", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListRenderingExtensions")
    @ResponseWrapper(localName = "ListRenderingExtensionsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ListRenderingExtensionsResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfExtension listRenderingExtensions();

    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "FindString", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.FindString")
    @WebMethod(operationName = "FindString", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/FindString")
    @ResponseWrapper(localName = "FindStringResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.FindStringResponse")
    public int findString(
        @WebParam(name = "StartPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int startPage,
        @WebParam(name = "EndPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int endPage,
        @WebParam(name = "FindValue", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String findValue
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetExecutionInfo2")
    @WebMethod(operationName = "GetExecutionInfo2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo2")
    @ResponseWrapper(localName = "GetExecutionInfo2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetExecutionInfo2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 getExecutionInfo2();

    @RequestWrapper(localName = "Render2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Render2")
    @WebMethod(operationName = "Render2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render2")
    @ResponseWrapper(localName = "Render2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Render2Response")
    public void render2(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.PageCountMode paginationMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> extension,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings,
        @WebParam(mode = WebParam.Mode.OUT, name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfString> streamIds
    );

    @WebResult(name = "result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetDocumentMap")
    @WebMethod(operationName = "GetDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetDocumentMap")
    @ResponseWrapper(localName = "GetDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.GetDocumentMapResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.DocumentMapNode getDocumentMap();

    @RequestWrapper(localName = "LogonUser", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LogonUser")
    @WebMethod(operationName = "LogonUser", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LogonUser")
    @ResponseWrapper(localName = "LogonUserResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LogonUserResponse")
    public void logonUser(
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String password,
        @WebParam(name = "authority", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String authority
    );

    @WebResult(name = "ListSecureMethodsResult", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListSecureMethods", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ListSecureMethods")
    @WebMethod(operationName = "ListSecureMethods", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListSecureMethods")
    @ResponseWrapper(localName = "ListSecureMethodsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ListSecureMethodsResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfString listSecureMethods();

    @RequestWrapper(localName = "NavigateBookmark", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.NavigateBookmark")
    @WebMethod(operationName = "NavigateBookmark", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateBookmark")
    @ResponseWrapper(localName = "NavigateBookmarkResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.NavigateBookmarkResponse")
    public void navigateBookmark(
        @WebParam(name = "BookmarkID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String bookmarkID,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "UniqueName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> uniqueName
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReport")
    @WebMethod(operationName = "LoadReport", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport")
    @ResponseWrapper(localName = "LoadReportResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReportResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo loadReport(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String historyID
    );

    @RequestWrapper(localName = "LoadReportDefinition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReportDefinition")
    @WebMethod(operationName = "LoadReportDefinition", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition")
    @ResponseWrapper(localName = "LoadReportDefinitionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.LoadReportDefinitionResponse")
    public void loadReportDefinition(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(mode = WebParam.Mode.OUT, name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo> executionInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings
    );

    @WebResult(name = "Found", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ToggleItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ToggleItem")
    @WebMethod(operationName = "ToggleItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ToggleItem")
    @ResponseWrapper(localName = "ToggleItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ToggleItemResponse")
    public boolean toggleItem(
        @WebParam(name = "ToggleID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String toggleID
    );

    @RequestWrapper(localName = "Sort", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.Sort")
    @WebMethod(operationName = "Sort", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort")
    @ResponseWrapper(localName = "SortResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortResponse")
    public void sort(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> reportItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "NumPages", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> numPages
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionParameters")
    @WebMethod(operationName = "SetExecutionParameters", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters")
    @ResponseWrapper(localName = "SetExecutionParametersResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionParametersResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo setExecutionParameters(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String parameterLanguage
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionCredentials2")
    @WebMethod(operationName = "SetExecutionCredentials2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials2")
    @ResponseWrapper(localName = "SetExecutionCredentials2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.SetExecutionCredentials2Response")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo2 setExecutionCredentials2(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ArrayOfDataSourceCredentials credentials
    );

    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ResetExecution")
    @WebMethod(operationName = "ResetExecution", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution")
    @ResponseWrapper(localName = "ResetExecutionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ResetExecutionResponse")
    public com.microsoft.schemas.sqlserver._2005._06._30.reporting.reportingservices.ExecutionInfo resetExecution();
}
